trigger:
- main # Trigger on changes to the main branch

pool:
  vmImage: 'windows-latest'

stages:
# Stage 1
- stage: Stage1
  displayName: "Stage 1 - Greeting"
  jobs:
  - job: Job1
    displayName: "Job 1 - Echo Hello"
    steps:
    - script: echo "Hello from Stage 1!"
      displayName: "Run echo script in Stage 1"

# Stage 2
- stage: SendEmail
  displayName: "Send Email Notification"
  dependsOn: Stage1
  condition: succeeded()
  variables:
    ACSConnectionString: 'endpoint=https://testcommadad112.unitedstates.communication.azure.com/;accesskey=D1YcpO2m6qu7eGXPXfA61rcsCqXbpuegCAw6MsIR5XYyHyDlZn75JQQJ99ALACULyCphoCslAAAAAZCSOsRw'
    RecipientEmails: 'olfa.khalij@mannai.com.qa'
    Subject: 'Deployment Succeeded'
    SenderEmail: 'DoNotReply@1aa1fbc6-3830-46f9-a434-ab9660f8d4c8.azurecomm.net'
  jobs:
  - job: InstallAzureCLI
    displayName: "Install Azure CLI"
    steps:
    - script: |
        echo Installing Azure CLI...
        powershell -Command "Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet /norestart' -NoNewWindow -Wait"
        echo Azure CLI installed successfully!
      displayName: "Install Azure CLI"

  - job: InstallCommunicationExtension
    displayName: "Install Communication Service Extension"
    dependsOn: InstallAzureCLI
    steps:
    - script: |
        echo Configuring Azure CLI for preview extensions...
        az config set extension.dynamic_install_allow_preview=true
        echo Installing Communication Extension...
        az extension add --name communication
        echo Communication Extension installed successfully!
      displayName: "Install Communication Extension"

  - job: SendEmailViaACS
    displayName: "Send Email via ACS"
    dependsOn: InstallCommunicationExtension
    steps:
    - script: |
       echo Sending email via Azure Communication Services...
        az communication email send `
          --sender "$(SenderEmail)" `
          --subject "$(Subject)" `
          --to "$(RecipientEmails)" `
          --text "Deployment succeeded for project: $(System.TeamProject).
Build ID: $(Build.BuildId).
          --connection-string "$(ACSConnectionString)"
     displayName: "Send Email Using Azure CLI"
