trigger:
- main # Change to your branch name

pool:
  vmImage: 'windows-latest' 

stages:
# Stage 1
- stage: Stage1
  displayName: "Stage 1 - Greeting"
  jobs:
  - job: Job1
    displayName: "Job 1 - Echo Hello"
    steps:
    - script: echo "Hello from Stage 1!"
      displayName: "Run echo script in Stage 1"

# Stage 2
- stage: Stage2
  displayName: "Stage 2 - Farewell"
  dependsOn: Stage1
  jobs:
  - job: Job2
    displayName: "Job 2 - Echo Goodbye"
    steps:
    - script: echo "Goodbye from Stage 2!"
      displayName: "Run echo script in Stage 2"

    - task: Bash@3
      name: SendEmailTask
      displayName: "Send Email via REST API"
      inputs:
        targetType: 'inline'
        script: |
          #!/bin/bash

          # Define email addresses, tfIds, and work item IDs
          emailAddresses=("Wiem.Belhaj@mannai.com.qa") # Replace with actual email address
          tfIds=()                                    # Leave empty if not using TFIDs
          workIDs=("workitemID")                      # Replace with the actual Work Item ID if applicable

          # Prepare the email body
          requestBody=$(cat <<EOF
          {
            "message": {
              "to": {
                "tfIds": [],
                "emailAddresses": ["${emailAddresses[0]}"],
                "unresolvedEntityIds": []
              },
              "subject": "This is a test subject",
              "body": "This is a test body",
              "cc": {
                "tfIds": []
              },
              "replyTo": {
                "tfIds": []
              }
            },
            "wiql": "SELECT [System.Id] FROM WorkItems WHERE [System.Id] = ${workIDs[0]}"
          }
          EOF
          )

          # Display the request body for debugging purposes
          echo "Request Body:"
          echo "$requestBody"

          # Send email via REST API using curl
          curl -X POST "$SYSTEM_TEAMFOUNDATIONSERVERURI$SYSTEM_TEAMPROJECT/_apis/wit/sendmail?api-version=7.0" \
               -H "Authorization: Basic $(echo -n ":$SYSTEM_ACCESSTOKEN" | base64)" \
               -H "Content-Type: application/json; charset=utf-8" \
               -d "$requestBody"
